version: '3'
services:
  jekyll-build:
    image: dagope/githubpagebase:v1.0
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c 'bundle install &&
             bundle exec jekyll serve --host 0.0.0.0 -w --force_polling --config "_config.yml"'