- title:
    it: Sviluppare Applicazioni enterprise con Node.js
    en: Building enterprise applications with Node.js
  period:
    start: "2017-02-09"
    end: "2017-02-10"
  note:
    it: Corso organizzato da Avanscoperta e tenuto da Matteo Collina.
    en: Course organized by Avanscoperta and taught by Matteo Collina.
- title:
    it: Agile Contracts - Esercizi sulla negoziazione nel contesto dei contratti
    en: Agile Contracts - Negotiation exercises in the context of contracts
  period:
    start: "2016-06-21"
    end: "2016-06-21"
  note:
    it: Corso organizzato da Avanscoperta e tenuto da Jacopo Romei.
    en: Course organized by Avanscoperta and taught by Jacopo Romei.
- title:
    it: PhpDay, JsDay, SymfonyDay e altre - conferenze italiane
    en: PhpDay, JsDay, SymfonyDay and others - Italian conferences
  period:
    start: "2009"
  note:
    it: Ho partecipato soprattutto a PhpDay, JsDay e SymfonyDay, a volte come volontario e una volta come speaker. Anche AgileDay, BetterSoftware, DevOpsDay e, più di recente, Working Software e SoCraTes Italy (settembre 2026).
    en: Attended mostly PhpDay, JsDay and SymfonyDay, sometimes as a volunteer and once as a speaker. Also AgileDay, BetterSoftware, DevOpsDay and, more recently, Working Software and SoCraTes Italy (September 2026).
