// Design tokens in one place: the values components are allowed to use.
// Colours come from palette.mjs, which owns the raw scale; spacing, fonts and
// the CSS shape live here. Both the site (src/styles/tokens.css) and the
// styleguide read from this module, so the preview cannot drift from the site.
// Documented in doc/STILE.md (SITE-16).

import { palette, semantic } from "./palette.mjs";

export const SPACE = [
  ["space-1", "0.25rem"],
  ["space-2", "0.5rem"],
  ["space-3", "0.75rem"],
  ["space-4", "1rem"],
  ["space-5", "1.5rem"],
  ["space-6", "2rem"],
  ["space-7", "3rem"],
  ["space-8", "4rem"],
  ["space-9", "6rem"],
];

export const FONTS = {
  sans: { family: "Public Sans", package: "public-sans" },
  mono: { family: "Commit Mono", package: "commit-mono" },
};

export const THEMES = ["light", "dark"];

export const themeTokens = (theme) =>
  Object.fromEntries(
    Object.keys(semantic).map((role) => [
      role,
      palette.get(semantic[role][theme]).hex,
    ]),
  );

const declarations = (entries, indent = "  ") =>
  entries.map(([name, value]) => `${indent}--${name}: ${value};`).join("\n");

const colourDeclarations = (theme, indent) =>
  declarations(Object.entries(themeTokens(theme)), indent);

export function tokensCss() {
  const fonts = [
    ["font-sans", `"${FONTS.sans.family}", system-ui, sans-serif`],
    ["font-mono", `"${FONTS.mono.family}", ui-monospace, monospace`],
  ];

  // Light on :root so anything that ignores the media query — print, a crawler,
  // a browser without JS — still gets a readable theme.
  return `/* Generated by tools/build-tokens.mjs. Do not edit: run npm run tokens. */

:root {
${declarations(fonts)}

${declarations(SPACE)}

${colourDeclarations("light")}
}

@media (prefers-color-scheme: dark) {
  :root {
${colourDeclarations("dark", "    ")}
  }
}

/* The theme toggle stamps data-theme on the root, and it wins over the media
   query in both directions. */
:root[data-theme="dark"] {
${colourDeclarations("dark")}
}

:root[data-theme="light"] {
${colourDeclarations("light")}
}

@media print {
  :root {
${colourDeclarations("light", "    ")}
  }
}
`;
}
